title: 'Meindert Heres Hoogerkamp'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
url: "https://econometrics.science"

header_pages:
  - index.md
  - about.md

style: dark

footer: 'connect with me on <a href="https://www.linkedin.com/in/meindert/">LinkedIn</a>'

# Build settings
markdown: kramdown
remote_theme: MeindertHH/jekyll-theme-console
