title: Meindert Heres Hoogerkamp
logo: https://media-exp1.licdn.com/dms/image/C4D03AQFmMzmZ6Xn-pg/profile-displayphoto-shrink_200_200/0?e=1588204800&v=beta&t=iSrY65J8eNKYUnXLPg9ry1P3C6Eqvvop5rW5CpY1f-Q
description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
